spring:
  application:
    name: authserver
    
  web:
    error:
      whitelabel:
        enabled: false
      include-message: always

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    use-root-path: true


