spring:
  application:
    name: authserver
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  web:
    error:
      whitelabel:
        enabled: false
      include-message: always
      include-binding-errors: always
      include-stacktrace: always
      include-exception: true

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    use-root-path: true

logging:
  file:
    path: ./logs

